export interface Emoji {
  emoji: string;
  name: string;
  category: string;
  tags: string[];
}

export const emojiData: Emoji[] = [
  { emoji: '😀', name: 'Grinning Face', category: 'Smileys', tags: ['happy', 'smile', 'grin'] },
  { emoji: '😃', name: 'Grinning Face with Big Eyes', category: 'Smileys', tags: ['happy', 'smile', 'joy'] },
  { emoji: '😄', name: 'Grinning Face with Smiling Eyes', category: 'Smileys', tags: ['happy', 'smile', 'laugh'] },
  { emoji: '😁', name: 'Beaming Face with Smiling Eyes', category: 'Smileys', tags: ['happy', 'smile', 'grin'] },
  { emoji: '😆', name: 'Grinning Squinting Face', category: 'Smileys', tags: ['laugh', 'happy', 'smile'] },
  { emoji: '😅', name: 'Grinning Face with Sweat', category: 'Smileys', tags: ['relief', 'sweat', 'smile'] },
  { emoji: '🤣', name: 'Rolling on the Floor Laughing', category: 'Smileys', tags: ['laugh', 'lol', 'rofl'] },
  { emoji: '😂', name: 'Face with Tears of Joy', category: 'Smileys', tags: ['laugh', 'joy', 'tears'] },
  { emoji: '🙂', name: 'Slightly Smiling Face', category: 'Smileys', tags: ['smile', 'happy'] },
  { emoji: '🙃', name: 'Upside-Down Face', category: 'Smileys', tags: ['silly', 'sarcasm'] },
  { emoji: '😉', name: 'Winking Face', category: 'Smileys', tags: ['wink', 'flirt'] },
  { emoji: '😊', name: 'Smiling Face with Smiling Eyes', category: 'Smileys', tags: ['smile', 'blush', 'happy'] },
  { emoji: '😇', name: 'Smiling Face with Halo', category: 'Smileys', tags: ['angel', 'innocent'] },
  { emoji: '🥰', name: 'Smiling Face with Hearts', category: 'Smileys', tags: ['love', 'hearts', 'smile'] },
  { emoji: '😍', name: 'Smiling Face with Heart-Eyes', category: 'Smileys', tags: ['love', 'hearts', 'crush'] },
  { emoji: '🤩', name: 'Star-Struck', category: 'Smileys', tags: ['star', 'eyes', 'wow'] },
  { emoji: '😘', name: 'Face Blowing a Kiss', category: 'Smileys', tags: ['kiss', 'love', 'flirt'] },
  { emoji: '😗', name: 'Kissing Face', category: 'Smileys', tags: ['kiss', 'love'] },
  { emoji: '😚', name: 'Kissing Face with Closed Eyes', category: 'Smileys', tags: ['kiss', 'love'] },
  { emoji: '😙', name: 'Kissing Face with Smiling Eyes', category: 'Smileys', tags: ['kiss', 'love', 'smile'] },
  { emoji: '😋', name: 'Face Savoring Food', category: 'Smileys', tags: ['yum', 'delicious', 'food'] },
  { emoji: '😛', name: 'Face with Tongue', category: 'Smileys', tags: ['tongue', 'silly'] },
  { emoji: '😜', name: 'Winking Face with Tongue', category: 'Smileys', tags: ['wink', 'tongue', 'silly'] },
  { emoji: '🤪', name: 'Zany Face', category: 'Smileys', tags: ['crazy', 'silly', 'wild'] },
  { emoji: '😝', name: 'Squinting Face with Tongue', category: 'Smileys', tags: ['tongue', 'silly', 'playful'] },
  { emoji: '🤑', name: 'Money-Mouth Face', category: 'Smileys', tags: ['money', 'rich', 'dollar'] },
  { emoji: '🤗', name: 'Hugging Face', category: 'Smileys', tags: ['hug', 'embrace'] },
  { emoji: '🤭', name: 'Face with Hand Over Mouth', category: 'Smileys', tags: ['oops', 'surprise'] },
  { emoji: '🤫', name: 'Shushing Face', category: 'Smileys', tags: ['quiet', 'silence', 'shh'] },
  { emoji: '🤔', name: 'Thinking Face', category: 'Smileys', tags: ['think', 'hmm', 'wonder'] },
  { emoji: '🤐', name: 'Zipper-Mouth Face', category: 'Smileys', tags: ['quiet', 'secret', 'silence'] },
  { emoji: '🤨', name: 'Face with Raised Eyebrow', category: 'Smileys', tags: ['skeptical', 'doubt'] },
  { emoji: '😐', name: 'Neutral Face', category: 'Smileys', tags: ['neutral', 'meh'] },
  { emoji: '😑', name: 'Expressionless Face', category: 'Smileys', tags: ['blank', 'meh'] },
  { emoji: '😶', name: 'Face Without Mouth', category: 'Smileys', tags: ['silence', 'quiet'] },
  { emoji: '😏', name: 'Smirking Face', category: 'Smileys', tags: ['smirk', 'smug'] },
  { emoji: '😒', name: 'Unamused Face', category: 'Smileys', tags: ['unamused', 'meh'] },
  { emoji: '🙄', name: 'Face with Rolling Eyes', category: 'Smileys', tags: ['eye roll', 'whatever'] },
  { emoji: '😬', name: 'Grimacing Face', category: 'Smileys', tags: ['grimace', 'awkward'] },
  { emoji: '🤥', name: 'Lying Face', category: 'Smileys', tags: ['lie', 'pinocchio'] },
  { emoji: '😌', name: 'Relieved Face', category: 'Smileys', tags: ['relief', 'calm'] },
  { emoji: '😔', name: 'Pensive Face', category: 'Smileys', tags: ['sad', 'pensive'] },
  { emoji: '😪', name: 'Sleepy Face', category: 'Smileys', tags: ['sleepy', 'tired'] },
  { emoji: '🤤', name: 'Drooling Face', category: 'Smileys', tags: ['drool', 'sleep'] },
  { emoji: '😴', name: 'Sleeping Face', category: 'Smileys', tags: ['sleep', 'zzz'] },
  { emoji: '😷', name: 'Face with Medical Mask', category: 'Smileys', tags: ['mask', 'sick', 'covid'] },
  { emoji: '🤒', name: 'Face with Thermometer', category: 'Smileys', tags: ['sick', 'ill', 'fever'] },
  { emoji: '🤕', name: 'Face with Head-Bandage', category: 'Smileys', tags: ['injured', 'hurt'] },
  { emoji: '🤢', name: 'Nauseated Face', category: 'Smileys', tags: ['sick', 'nausea'] },
  { emoji: '🤮', name: 'Face Vomiting', category: 'Smileys', tags: ['vomit', 'sick'] },
  { emoji: '🤧', name: 'Sneezing Face', category: 'Smileys', tags: ['sneeze', 'sick'] },
  { emoji: '🥵', name: 'Hot Face', category: 'Smileys', tags: ['hot', 'heat'] },
  { emoji: '🥶', name: 'Cold Face', category: 'Smileys', tags: ['cold', 'freezing'] },
  { emoji: '😵', name: 'Dizzy Face', category: 'Smileys', tags: ['dizzy', 'confused'] },
  { emoji: '🤯', name: 'Exploding Head', category: 'Smileys', tags: ['mind blown', 'shocked'] },
  { emoji: '😎', name: 'Smiling Face with Sunglasses', category: 'Smileys', tags: ['cool', 'sunglasses'] },
  { emoji: '🤓', name: 'Nerd Face', category: 'Smileys', tags: ['nerd', 'geek', 'smart'] },
  { emoji: '🧐', name: 'Face with Monocle', category: 'Smileys', tags: ['monocle', 'fancy'] },
  { emoji: '😕', name: 'Confused Face', category: 'Smileys', tags: ['confused', 'puzzled'] },
  { emoji: '😟', name: 'Worried Face', category: 'Smileys', tags: ['worry', 'concerned'] },
  { emoji: '🙁', name: 'Slightly Frowning Face', category: 'Smileys', tags: ['sad', 'frown'] },
  { emoji: '☹️', name: 'Frowning Face', category: 'Smileys', tags: ['sad', 'frown'] },
  { emoji: '😮', name: 'Face with Open Mouth', category: 'Smileys', tags: ['surprise', 'wow'] },
  { emoji: '😯', name: 'Hushed Face', category: 'Smileys', tags: ['surprise', 'quiet'] },
  { emoji: '😲', name: 'Astonished Face', category: 'Smileys', tags: ['shock', 'surprise'] },
  { emoji: '😳', name: 'Flushed Face', category: 'Smileys', tags: ['blush', 'embarrassed'] },
  { emoji: '🥺', name: 'Pleading Face', category: 'Smileys', tags: ['plead', 'puppy eyes'] },
  { emoji: '😦', name: 'Frowning Face with Open Mouth', category: 'Smileys', tags: ['frown', 'sad'] },
  { emoji: '😧', name: 'Anguished Face', category: 'Smileys', tags: ['anguish', 'pain'] },
  { emoji: '😨', name: 'Fearful Face', category: 'Smileys', tags: ['fear', 'scared'] },
  { emoji: '😰', name: 'Anxious Face with Sweat', category: 'Smileys', tags: ['anxious', 'nervous'] },
  { emoji: '😥', name: 'Sad but Relieved Face', category: 'Smileys', tags: ['sad', 'relief'] },
  { emoji: '😢', name: 'Crying Face', category: 'Smileys', tags: ['cry', 'sad', 'tears'] },
  { emoji: '😭', name: 'Loudly Crying Face', category: 'Smileys', tags: ['cry', 'sob', 'tears'] },
  { emoji: '😱', name: 'Face Screaming in Fear', category: 'Smileys', tags: ['scream', 'fear'] },
  { emoji: '😖', name: 'Confounded Face', category: 'Smileys', tags: ['confused', 'frustrated'] },
  { emoji: '😣', name: 'Persevering Face', category: 'Smileys', tags: ['struggle', 'effort'] },
  { emoji: '😞', name: 'Disappointed Face', category: 'Smileys', tags: ['disappointed', 'sad'] },
  { emoji: '😓', name: 'Downcast Face with Sweat', category: 'Smileys', tags: ['sweat', 'stress'] },
  { emoji: '😩', name: 'Weary Face', category: 'Smileys', tags: ['tired', 'weary'] },
  { emoji: '😫', name: 'Tired Face', category: 'Smileys', tags: ['tired', 'exhausted'] },
  { emoji: '🥱', name: 'Yawning Face', category: 'Smileys', tags: ['yawn', 'tired', 'bored'] },
  { emoji: '😤', name: 'Face with Steam From Nose', category: 'Smileys', tags: ['angry', 'frustrated'] },
  { emoji: '😡', name: 'Pouting Face', category: 'Smileys', tags: ['angry', 'mad'] },
  { emoji: '😠', name: 'Angry Face', category: 'Smileys', tags: ['angry', 'mad'] },
  { emoji: '🤬', name: 'Face with Symbols on Mouth', category: 'Smileys', tags: ['swear', 'curse', 'angry'] },
  { emoji: '😈', name: 'Smiling Face with Horns', category: 'Smileys', tags: ['devil', 'evil', 'naughty'] },
  { emoji: '👿', name: 'Angry Face with Horns', category: 'Smileys', tags: ['devil', 'evil', 'angry'] },
  { emoji: '💀', name: 'Skull', category: 'Smileys', tags: ['death', 'skull', 'dead'] },
  { emoji: '☠️', name: 'Skull and Crossbones', category: 'Smileys', tags: ['death', 'danger', 'poison'] },

  { emoji: '❤️', name: 'Red Heart', category: 'Hearts', tags: ['love', 'heart', 'red'] },
  { emoji: '🧡', name: 'Orange Heart', category: 'Hearts', tags: ['love', 'heart', 'orange'] },
  { emoji: '💛', name: 'Yellow Heart', category: 'Hearts', tags: ['love', 'heart', 'yellow'] },
  { emoji: '💚', name: 'Green Heart', category: 'Hearts', tags: ['love', 'heart', 'green'] },
  { emoji: '💙', name: 'Blue Heart', category: 'Hearts', tags: ['love', 'heart', 'blue'] },
  { emoji: '💜', name: 'Purple Heart', category: 'Hearts', tags: ['love', 'heart', 'purple'] },
  { emoji: '🖤', name: 'Black Heart', category: 'Hearts', tags: ['love', 'heart', 'black'] },
  { emoji: '🤍', name: 'White Heart', category: 'Hearts', tags: ['love', 'heart', 'white'] },
  { emoji: '🤎', name: 'Brown Heart', category: 'Hearts', tags: ['love', 'heart', 'brown'] },
  { emoji: '💔', name: 'Broken Heart', category: 'Hearts', tags: ['broken', 'heart', 'sad'] },
  { emoji: '💕', name: 'Two Hearts', category: 'Hearts', tags: ['love', 'hearts'] },
  { emoji: '💞', name: 'Revolving Hearts', category: 'Hearts', tags: ['love', 'hearts'] },
  { emoji: '💓', name: 'Beating Heart', category: 'Hearts', tags: ['love', 'heart', 'beat'] },
  { emoji: '💗', name: 'Growing Heart', category: 'Hearts', tags: ['love', 'heart', 'grow'] },
  { emoji: '💖', name: 'Sparkling Heart', category: 'Hearts', tags: ['love', 'heart', 'sparkle'] },
  { emoji: '💘', name: 'Heart with Arrow', category: 'Hearts', tags: ['love', 'cupid', 'heart'] },
  { emoji: '💝', name: 'Heart with Ribbon', category: 'Hearts', tags: ['love', 'gift', 'heart'] },

  { emoji: '👋', name: 'Waving Hand', category: 'Gestures', tags: ['wave', 'hello', 'hi'] },
  { emoji: '🤚', name: 'Raised Back of Hand', category: 'Gestures', tags: ['hand', 'stop'] },
  { emoji: '🖐️', name: 'Hand with Fingers Splayed', category: 'Gestures', tags: ['hand', 'five'] },
  { emoji: '✋', name: 'Raised Hand', category: 'Gestures', tags: ['hand', 'stop', 'high five'] },
  { emoji: '🖖', name: 'Vulcan Salute', category: 'Gestures', tags: ['spock', 'star trek'] },
  { emoji: '👌', name: 'OK Hand', category: 'Gestures', tags: ['ok', 'okay', 'good'] },
  { emoji: '🤏', name: 'Pinching Hand', category: 'Gestures', tags: ['pinch', 'small'] },
  { emoji: '✌️', name: 'Victory Hand', category: 'Gestures', tags: ['peace', 'victory'] },
  { emoji: '🤞', name: 'Crossed Fingers', category: 'Gestures', tags: ['fingers crossed', 'luck'] },
  { emoji: '🤟', name: 'Love-You Gesture', category: 'Gestures', tags: ['love', 'rock'] },
  { emoji: '🤘', name: 'Sign of the Horns', category: 'Gestures', tags: ['rock', 'metal'] },
  { emoji: '🤙', name: 'Call Me Hand', category: 'Gestures', tags: ['call', 'phone', 'shaka'] },
  { emoji: '��', name: 'Backhand Index Pointing Left', category: 'Gestures', tags: ['point', 'left'] },
  { emoji: '👉', name: 'Backhand Index Pointing Right', category: 'Gestures', tags: ['point', 'right'] },
  { emoji: '👆', name: 'Backhand Index Pointing Up', category: 'Gestures', tags: ['point', 'up'] },
  { emoji: '👇', name: 'Backhand Index Pointing Down', category: 'Gestures', tags: ['point', 'down'] },
  { emoji: '☝️', name: 'Index Pointing Up', category: 'Gestures', tags: ['point', 'up', 'one'] },
  { emoji: '👍', name: 'Thumbs Up', category: 'Gestures', tags: ['thumbs up', 'like', 'good'] },
  { emoji: '👎', name: 'Thumbs Down', category: 'Gestures', tags: ['thumbs down', 'dislike', 'bad'] },
  { emoji: '✊', name: 'Raised Fist', category: 'Gestures', tags: ['fist', 'power'] },
  { emoji: '👊', name: 'Oncoming Fist', category: 'Gestures', tags: ['fist', 'bump', 'punch'] },
  { emoji: '🤛', name: 'Left-Facing Fist', category: 'Gestures', tags: ['fist', 'bump', 'left'] },
  { emoji: '🤜', name: 'Right-Facing Fist', category: 'Gestures', tags: ['fist', 'bump', 'right'] },
  { emoji: '👏', name: 'Clapping Hands', category: 'Gestures', tags: ['clap', 'applause'] },
  { emoji: '🙌', name: 'Raising Hands', category: 'Gestures', tags: ['hands', 'celebrate', 'yay'] },
  { emoji: '👐', name: 'Open Hands', category: 'Gestures', tags: ['hands', 'open'] },
  { emoji: '🤲', name: 'Palms Up Together', category: 'Gestures', tags: ['hands', 'pray', 'offer'] },
  { emoji: '🤝', name: 'Handshake', category: 'Gestures', tags: ['handshake', 'deal', 'agreement'] },
  { emoji: '🙏', name: 'Folded Hands', category: 'Gestures', tags: ['pray', 'thank you', 'namaste'] },

  { emoji: '🐶', name: 'Dog Face', category: 'Animals', tags: ['dog', 'puppy', 'pet'] },
  { emoji: '🐱', name: 'Cat Face', category: 'Animals', tags: ['cat', 'kitten', 'pet'] },
  { emoji: '🐭', name: 'Mouse Face', category: 'Animals', tags: ['mouse', 'rat'] },
  { emoji: '🐹', name: 'Hamster', category: 'Animals', tags: ['hamster', 'pet'] },
  { emoji: '🐰', name: 'Rabbit Face', category: 'Animals', tags: ['rabbit', 'bunny'] },
  { emoji: '🦊', name: 'Fox', category: 'Animals', tags: ['fox'] },
  { emoji: '🐻', name: 'Bear', category: 'Animals', tags: ['bear'] },
  { emoji: '🐼', name: 'Panda', category: 'Animals', tags: ['panda', 'bear'] },
  { emoji: '🐨', name: 'Koala', category: 'Animals', tags: ['koala', 'australia'] },
  { emoji: '🐯', name: 'Tiger Face', category: 'Animals', tags: ['tiger', 'cat'] },
  { emoji: '🦁', name: 'Lion', category: 'Animals', tags: ['lion', 'king'] },
  { emoji: '🐮', name: 'Cow Face', category: 'Animals', tags: ['cow', 'cattle'] },
  { emoji: '🐷', name: 'Pig Face', category: 'Animals', tags: ['pig', 'pork'] },
  { emoji: '🐸', name: 'Frog', category: 'Animals', tags: ['frog', 'toad'] },
  { emoji: '🐵', name: 'Monkey Face', category: 'Animals', tags: ['monkey', 'ape'] },
  { emoji: '🙈', name: 'See-No-Evil Monkey', category: 'Animals', tags: ['monkey', 'see no evil'] },
  { emoji: '🙉', name: 'Hear-No-Evil Monkey', category: 'Animals', tags: ['monkey', 'hear no evil'] },
  { emoji: '🙊', name: 'Speak-No-Evil Monkey', category: 'Animals', tags: ['monkey', 'speak no evil'] },
  { emoji: '🐒', name: 'Monkey', category: 'Animals', tags: ['monkey'] },
  { emoji: '🐔', name: 'Chicken', category: 'Animals', tags: ['chicken', 'bird'] },
  { emoji: '🐧', name: 'Penguin', category: 'Animals', tags: ['penguin', 'bird'] },
  { emoji: '🐦', name: 'Bird', category: 'Animals', tags: ['bird'] },
  { emoji: '🐤', name: 'Baby Chick', category: 'Animals', tags: ['chick', 'baby', 'bird'] },
  { emoji: '🦆', name: 'Duck', category: 'Animals', tags: ['duck', 'bird'] },
  { emoji: '🦅', name: 'Eagle', category: 'Animals', tags: ['eagle', 'bird'] },
  { emoji: '🦉', name: 'Owl', category: 'Animals', tags: ['owl', 'bird', 'wise'] },
  { emoji: '🦇', name: 'Bat', category: 'Animals', tags: ['bat', 'vampire'] },
  { emoji: '🐺', name: 'Wolf', category: 'Animals', tags: ['wolf', 'dog'] },
  { emoji: '🐗', name: 'Boar', category: 'Animals', tags: ['boar', 'pig'] },
  { emoji: '🐴', name: 'Horse Face', category: 'Animals', tags: ['horse'] },
  { emoji: '🦄', name: 'Unicorn', category: 'Animals', tags: ['unicorn', 'magic'] },
  { emoji: '🐝', name: 'Honeybee', category: 'Animals', tags: ['bee', 'honey'] },
  { emoji: '🐛', name: 'Bug', category: 'Animals', tags: ['bug', 'insect'] },
  { emoji: '🦋', name: 'Butterfly', category: 'Animals', tags: ['butterfly', 'insect'] },
  { emoji: '🐌', name: 'Snail', category: 'Animals', tags: ['snail', 'slow'] },
  { emoji: '🐞', name: 'Lady Beetle', category: 'Animals', tags: ['ladybug', 'insect'] },
  { emoji: '🐜', name: 'Ant', category: 'Animals', tags: ['ant', 'insect'] },
  { emoji: '🦗', name: 'Cricket', category: 'Animals', tags: ['cricket', 'insect'] },
  { emoji: '🕷️', name: 'Spider', category: 'Animals', tags: ['spider', 'insect'] },
  { emoji: '🦂', name: 'Scorpion', category: 'Animals', tags: ['scorpion'] },
  { emoji: '🐢', name: 'Turtle', category: 'Animals', tags: ['turtle', 'slow'] },
  { emoji: '🐍', name: 'Snake', category: 'Animals', tags: ['snake', 'serpent'] },
  { emoji: '🦎', name: 'Lizard', category: 'Animals', tags: ['lizard', 'reptile'] },
  { emoji: '🦖', name: 'T-Rex', category: 'Animals', tags: ['dinosaur', 'trex'] },
  { emoji: '🦕', name: 'Sauropod', category: 'Animals', tags: ['dinosaur'] },
  { emoji: '🐙', name: 'Octopus', category: 'Animals', tags: ['octopus', 'sea'] },
  { emoji: '🦑', name: 'Squid', category: 'Animals', tags: ['squid', 'sea'] },
  { emoji: '🦐', name: 'Shrimp', category: 'Animals', tags: ['shrimp', 'sea'] },
  { emoji: '🦞', name: 'Lobster', category: 'Animals', tags: ['lobster', 'sea'] },
  { emoji: '🦀', name: 'Crab', category: 'Animals', tags: ['crab', 'sea'] },
  { emoji: '🐡', name: 'Blowfish', category: 'Animals', tags: ['fish', 'blowfish'] },
  { emoji: '🐠', name: 'Tropical Fish', category: 'Animals', tags: ['fish', 'tropical'] },
  { emoji: '🐟', name: 'Fish', category: 'Animals', tags: ['fish'] },
  { emoji: '🐬', name: 'Dolphin', category: 'Animals', tags: ['dolphin', 'sea'] },
  { emoji: '🐳', name: 'Spouting Whale', category: 'Animals', tags: ['whale', 'sea'] },
  { emoji: '🐋', name: 'Whale', category: 'Animals', tags: ['whale', 'sea'] },
  { emoji: '🦈', name: 'Shark', category: 'Animals', tags: ['shark', 'sea', 'danger'] },

  { emoji: '🍎', name: 'Red Apple', category: 'Food', tags: ['apple', 'fruit', 'red'] },
  { emoji: '🍊', name: 'Tangerine', category: 'Food', tags: ['orange', 'fruit'] },
  { emoji: '🍋', name: 'Lemon', category: 'Food', tags: ['lemon', 'fruit', 'sour'] },
  { emoji: '🍌', name: 'Banana', category: 'Food', tags: ['banana', 'fruit'] },
  { emoji: '🍉', name: 'Watermelon', category: 'Food', tags: ['watermelon', 'fruit'] },
  { emoji: '🍇', name: 'Grapes', category: 'Food', tags: ['grapes', 'fruit'] },
  { emoji: '🍓', name: 'Strawberry', category: 'Food', tags: ['strawberry', 'fruit', 'berry'] },
  { emoji: '🍒', name: 'Cherries', category: 'Food', tags: ['cherry', 'fruit'] },
  { emoji: '🍑', name: 'Peach', category: 'Food', tags: ['peach', 'fruit'] },
  { emoji: '🥭', name: 'Mango', category: 'Food', tags: ['mango', 'fruit'] },
  { emoji: '🍍', name: 'Pineapple', category: 'Food', tags: ['pineapple', 'fruit'] },
  { emoji: '🥥', name: 'Coconut', category: 'Food', tags: ['coconut', 'fruit'] },
  { emoji: '🥝', name: 'Kiwi Fruit', category: 'Food', tags: ['kiwi', 'fruit'] },
  { emoji: '🍅', name: 'Tomato', category: 'Food', tags: ['tomato', 'vegetable'] },
  { emoji: '🍆', name: 'Eggplant', category: 'Food', tags: ['eggplant', 'vegetable'] },
  { emoji: '🥑', name: 'Avocado', category: 'Food', tags: ['avocado', 'fruit'] },
  { emoji: '🥦', name: 'Broccoli', category: 'Food', tags: ['broccoli', 'vegetable'] },
  { emoji: '🥬', name: 'Leafy Green', category: 'Food', tags: ['lettuce', 'vegetable', 'green'] },
  { emoji: '🥒', name: 'Cucumber', category: 'Food', tags: ['cucumber', 'vegetable'] },
  { emoji: '🌶️', name: 'Hot Pepper', category: 'Food', tags: ['pepper', 'spicy', 'hot'] },
  { emoji: '🌽', name: 'Ear of Corn', category: 'Food', tags: ['corn', 'vegetable'] },
  { emoji: '🥕', name: 'Carrot', category: 'Food', tags: ['carrot', 'vegetable'] },
  { emoji: '🥔', name: 'Potato', category: 'Food', tags: ['potato', 'vegetable'] },
  { emoji: '🍠', name: 'Roasted Sweet Potato', category: 'Food', tags: ['sweet potato', 'yam'] },
  { emoji: '🍞', name: 'Bread', category: 'Food', tags: ['bread', 'bakery'] },
  { emoji: '🥐', name: 'Croissant', category: 'Food', tags: ['croissant', 'bread', 'bakery'] },
  { emoji: '🥖', name: 'Baguette Bread', category: 'Food', tags: ['baguette', 'bread', 'french'] },
  { emoji: '🥨', name: 'Pretzel', category: 'Food', tags: ['pretzel', 'snack'] },
  { emoji: '🥯', name: 'Bagel', category: 'Food', tags: ['bagel', 'bread'] },
  { emoji: '🧀', name: 'Cheese Wedge', category: 'Food', tags: ['cheese', 'dairy'] },
  { emoji: '🥚', name: 'Egg', category: 'Food', tags: ['egg'] },
  { emoji: '🍳', name: 'Cooking', category: 'Food', tags: ['egg', 'cooking', 'frying'] },
  { emoji: '🥓', name: 'Bacon', category: 'Food', tags: ['bacon', 'meat'] },
  { emoji: '🥩', name: 'Cut of Meat', category: 'Food', tags: ['meat', 'steak'] },
  { emoji: '🍗', name: 'Poultry Leg', category: 'Food', tags: ['chicken', 'meat', 'drumstick'] },
  { emoji: '🍖', name: 'Meat on Bone', category: 'Food', tags: ['meat', 'bone'] },
  { emoji: '🌭', name: 'Hot Dog', category: 'Food', tags: ['hotdog', 'sausage'] },
  { emoji: '🍔', name: 'Hamburger', category: 'Food', tags: ['burger', 'hamburger', 'fast food'] },
  { emoji: '🍟', name: 'French Fries', category: 'Food', tags: ['fries', 'french fries', 'fast food'] },
  { emoji: '🍕', name: 'Pizza', category: 'Food', tags: ['pizza', 'slice'] },
  { emoji: '🥪', name: 'Sandwich', category: 'Food', tags: ['sandwich', 'sub'] },
  { emoji: '🥙', name: 'Stuffed Flatbread', category: 'Food', tags: ['kebab', 'wrap'] },
  { emoji: '🌮', name: 'Taco', category: 'Food', tags: ['taco', 'mexican'] },
  { emoji: '🌯', name: 'Burrito', category: 'Food', tags: ['burrito', 'mexican', 'wrap'] },
  { emoji: '🥗', name: 'Green Salad', category: 'Food', tags: ['salad', 'healthy', 'green'] },
  { emoji: '🍝', name: 'Spaghetti', category: 'Food', tags: ['pasta', 'spaghetti', 'italian'] },
  { emoji: '🍜', name: 'Steaming Bowl', category: 'Food', tags: ['ramen', 'noodles', 'soup'] },
  { emoji: '🍲', name: 'Pot of Food', category: 'Food', tags: ['stew', 'pot', 'food'] },
  { emoji: '🍛', name: 'Curry Rice', category: 'Food', tags: ['curry', 'rice', 'indian'] },
  { emoji: '🍣', name: 'Sushi', category: 'Food', tags: ['sushi', 'japanese', 'fish'] },
  { emoji: '🍱', name: 'Bento Box', category: 'Food', tags: ['bento', 'japanese', 'lunch'] },
  { emoji: '🥟', name: 'Dumpling', category: 'Food', tags: ['dumpling', 'gyoza'] },
  { emoji: '🍤', name: 'Fried Shrimp', category: 'Food', tags: ['shrimp', 'fried', 'tempura'] },
  { emoji: '🍙', name: 'Rice Ball', category: 'Food', tags: ['rice', 'onigiri', 'japanese'] },
  { emoji: '🍚', name: 'Cooked Rice', category: 'Food', tags: ['rice', 'bowl'] },
  { emoji: '🍘', name: 'Rice Cracker', category: 'Food', tags: ['rice', 'cracker', 'snack'] },
  { emoji: '🍥', name: 'Fish Cake with Swirl', category: 'Food', tags: ['fish cake', 'naruto'] },
  { emoji: '🥠', name: 'Fortune Cookie', category: 'Food', tags: ['cookie', 'fortune'] },
  { emoji: '🥮', name: 'Moon Cake', category: 'Food', tags: ['moon cake', 'chinese'] },
  { emoji: '🍢', name: 'Oden', category: 'Food', tags: ['oden', 'japanese', 'skewer'] },
  { emoji: '🍡', name: 'Dango', category: 'Food', tags: ['dango', 'japanese', 'sweet'] },
  { emoji: '🍧', name: 'Shaved Ice', category: 'Food', tags: ['ice', 'dessert', 'shaved'] },
  { emoji: '🍨', name: 'Ice Cream', category: 'Food', tags: ['ice cream', 'dessert'] },
  { emoji: '🍦', name: 'Soft Ice Cream', category: 'Food', tags: ['ice cream', 'soft serve', 'dessert'] },
  { emoji: '🥧', name: 'Pie', category: 'Food', tags: ['pie', 'dessert'] },
  { emoji: '🧁', name: 'Cupcake', category: 'Food', tags: ['cupcake', 'dessert', 'muffin'] },
  { emoji: '🍰', name: 'Shortcake', category: 'Food', tags: ['cake', 'dessert', 'slice'] },
  { emoji: '🎂', name: 'Birthday Cake', category: 'Food', tags: ['cake', 'birthday', 'celebration'] },
  { emoji: '🍮', name: 'Custard', category: 'Food', tags: ['custard', 'pudding', 'flan'] },
  { emoji: '🍭', name: 'Lollipop', category: 'Food', tags: ['lollipop', 'candy', 'sweet'] },
  { emoji: '🍬', name: 'Candy', category: 'Food', tags: ['candy', 'sweet'] },
  { emoji: '🍫', name: 'Chocolate Bar', category: 'Food', tags: ['chocolate', 'candy'] },
  { emoji: '🍿', name: 'Popcorn', category: 'Food', tags: ['popcorn', 'snack', 'movie'] },
  { emoji: '🍩', name: 'Doughnut', category: 'Food', tags: ['donut', 'doughnut', 'dessert'] },
  { emoji: '🍪', name: 'Cookie', category: 'Food', tags: ['cookie', 'dessert'] },

  { emoji: '⚽', name: 'Soccer Ball', category: 'Sports', tags: ['soccer', 'football', 'ball'] },
  { emoji: '🏀', name: 'Basketball', category: 'Sports', tags: ['basketball', 'ball'] },
  { emoji: '🏈', name: 'American Football', category: 'Sports', tags: ['football', 'ball', 'american'] },
  { emoji: '⚾', name: 'Baseball', category: 'Sports', tags: ['baseball', 'ball'] },
  { emoji: '🎾', name: 'Tennis', category: 'Sports', tags: ['tennis', 'ball'] },
  { emoji: '🏐', name: 'Volleyball', category: 'Sports', tags: ['volleyball', 'ball'] },
  { emoji: '🏉', name: 'Rugby Football', category: 'Sports', tags: ['rugby', 'ball'] },
  { emoji: '🎱', name: 'Pool 8 Ball', category: 'Sports', tags: ['pool', 'billiards', '8ball'] },
  { emoji: '🏓', name: 'Ping Pong', category: 'Sports', tags: ['ping pong', 'table tennis'] },
  { emoji: '🏸', name: 'Badminton', category: 'Sports', tags: ['badminton', 'shuttlecock'] },
  { emoji: '🥅', name: 'Goal Net', category: 'Sports', tags: ['goal', 'net', 'soccer'] },
  { emoji: '🏒', name: 'Ice Hockey', category: 'Sports', tags: ['hockey', 'ice'] },
  { emoji: '🏑', name: 'Field Hockey', category: 'Sports', tags: ['hockey', 'field'] },
  { emoji: '🥍', name: 'Lacrosse', category: 'Sports', tags: ['lacrosse'] },
  { emoji: '🏏', name: 'Cricket Game', category: 'Sports', tags: ['cricket', 'bat'] },
  { emoji: '🥊', name: 'Boxing Glove', category: 'Sports', tags: ['boxing', 'glove', 'fight'] },
  { emoji: '🥋', name: 'Martial Arts Uniform', category: 'Sports', tags: ['martial arts', 'karate', 'judo'] },
  { emoji: '⛳', name: 'Flag in Hole', category: 'Sports', tags: ['golf', 'flag'] },
  { emoji: '🏹', name: 'Bow and Arrow', category: 'Sports', tags: ['archery', 'bow', 'arrow'] },
  { emoji: '🎣', name: 'Fishing Pole', category: 'Sports', tags: ['fishing', 'pole'] },
  { emoji: '🥊', name: 'Boxing Glove', category: 'Sports', tags: ['boxing', 'punch'] },
  { emoji: '🎿', name: 'Skis', category: 'Sports', tags: ['ski', 'snow'] },
  { emoji: '🛷', name: 'Sled', category: 'Sports', tags: ['sled', 'snow'] },
  { emoji: '⛸️', name: 'Ice Skate', category: 'Sports', tags: ['ice skate', 'skating'] },

  { emoji: '🚗', name: 'Automobile', category: 'Transport', tags: ['car', 'vehicle', 'auto'] },
  { emoji: '🚕', name: 'Taxi', category: 'Transport', tags: ['taxi', 'cab', 'car'] },
  { emoji: '🚙', name: 'Sport Utility Vehicle', category: 'Transport', tags: ['suv', 'car', 'vehicle'] },
  { emoji: '🚌', name: 'Bus', category: 'Transport', tags: ['bus', 'vehicle'] },
  { emoji: '🚎', name: 'Trolleybus', category: 'Transport', tags: ['trolley', 'bus'] },
  { emoji: '🏎️', name: 'Racing Car', category: 'Transport', tags: ['race car', 'racing', 'fast'] },
  { emoji: '🚓', name: 'Police Car', category: 'Transport', tags: ['police', 'car', 'cop'] },
  { emoji: '🚑', name: 'Ambulance', category: 'Transport', tags: ['ambulance', 'emergency'] },
  { emoji: '🚒', name: 'Fire Engine', category: 'Transport', tags: ['fire truck', 'fire', 'emergency'] },
  { emoji: '🚐', name: 'Minibus', category: 'Transport', tags: ['minibus', 'van'] },
  { emoji: '🚚', name: 'Delivery Truck', category: 'Transport', tags: ['truck', 'delivery'] },
  { emoji: '🚛', name: 'Articulated Lorry', category: 'Transport', tags: ['truck', 'semi', 'lorry'] },
  { emoji: '🚜', name: 'Tractor', category: 'Transport', tags: ['tractor', 'farm'] },
  { emoji: '🏍️', name: 'Motorcycle', category: 'Transport', tags: ['motorcycle', 'bike'] },
  { emoji: '🛵', name: 'Motor Scooter', category: 'Transport', tags: ['scooter', 'vespa'] },
  { emoji: '🚲', name: 'Bicycle', category: 'Transport', tags: ['bicycle', 'bike', 'cycle'] },
  { emoji: '🛴', name: 'Kick Scooter', category: 'Transport', tags: ['scooter', 'kick'] },
  { emoji: '✈️', name: 'Airplane', category: 'Transport', tags: ['airplane', 'plane', 'flight'] },
  { emoji: '🚁', name: 'Helicopter', category: 'Transport', tags: ['helicopter', 'chopper'] },
  { emoji: '🚂', name: 'Locomotive', category: 'Transport', tags: ['train', 'locomotive'] },
  { emoji: '🚆', name: 'Train', category: 'Transport', tags: ['train', 'railway'] },
  { emoji: '🚇', name: 'Metro', category: 'Transport', tags: ['metro', 'subway'] },
  { emoji: '🚊', name: 'Tram', category: 'Transport', tags: ['tram', 'streetcar'] },
  { emoji: '🚝', name: 'Monorail', category: 'Transport', tags: ['monorail', 'train'] },
  { emoji: '🚄', name: 'High-Speed Train', category: 'Transport', tags: ['bullet train', 'fast', 'shinkansen'] },
  { emoji: '🚅', name: 'Bullet Train', category: 'Transport', tags: ['bullet train', 'fast', 'train'] },
  { emoji: '🚈', name: 'Light Rail', category: 'Transport', tags: ['light rail', 'train'] },
  { emoji: '🚞', name: 'Mountain Railway', category: 'Transport', tags: ['mountain', 'railway', 'train'] },
  { emoji: '🚋', name: 'Tram Car', category: 'Transport', tags: ['tram', 'streetcar'] },
  { emoji: '🚃', name: 'Railway Car', category: 'Transport', tags: ['train', 'railway', 'car'] },
  { emoji: '🚟', name: 'Suspension Railway', category: 'Transport', tags: ['suspension', 'railway'] },
  { emoji: '🚠', name: 'Mountain Cableway', category: 'Transport', tags: ['cable', 'car', 'mountain'] },
  { emoji: '🚡', name: 'Aerial Tramway', category: 'Transport', tags: ['tramway', 'cable', 'car'] },
  { emoji: '🚢', name: 'Ship', category: 'Transport', tags: ['ship', 'boat', 'sea'] },
  { emoji: '⛵', name: 'Sailboat', category: 'Transport', tags: ['sailboat', 'boat', 'sail'] },
  { emoji: '🚤', name: 'Speedboat', category: 'Transport', tags: ['speedboat', 'boat', 'fast'] },
  { emoji: '🛥️', name: 'Motor Boat', category: 'Transport', tags: ['motorboat', 'boat'] },
  { emoji: '🛳️', name: 'Passenger Ship', category: 'Transport', tags: ['cruise', 'ship', 'passenger'] },
  { emoji: '⛴️', name: 'Ferry', category: 'Transport', tags: ['ferry', 'boat'] },
  { emoji: '🚀', name: 'Rocket', category: 'Transport', tags: ['rocket', 'space', 'launch'] },
  { emoji: '🛸', name: 'Flying Saucer', category: 'Transport', tags: ['ufo', 'alien', 'saucer'] },

  { emoji: '⌚', name: 'Watch', category: 'Objects', tags: ['watch', 'time'] },
  { emoji: '📱', name: 'Mobile Phone', category: 'Objects', tags: ['phone', 'mobile', 'cell'] },
  { emoji: '💻', name: 'Laptop', category: 'Objects', tags: ['laptop', 'computer'] },
  { emoji: '⌨️', name: 'Keyboard', category: 'Objects', tags: ['keyboard', 'computer'] },
  { emoji: '🖥️', name: 'Desktop Computer', category: 'Objects', tags: ['desktop', 'computer'] },
  { emoji: '🖨️', name: 'Printer', category: 'Objects', tags: ['printer', 'print'] },
  { emoji: '🖱️', name: 'Computer Mouse', category: 'Objects', tags: ['mouse', 'computer'] },
  { emoji: '🖲️', name: 'Trackball', category: 'Objects', tags: ['trackball', 'mouse'] },
  { emoji: '💾', name: 'Floppy Disk', category: 'Objects', tags: ['floppy', 'disk', 'save'] },
  { emoji: '💿', name: 'Optical Disk', category: 'Objects', tags: ['cd', 'disk'] },
  { emoji: '📀', name: 'DVD', category: 'Objects', tags: ['dvd', 'disk'] },
  { emoji: '🎥', name: 'Movie Camera', category: 'Objects', tags: ['camera', 'movie', 'film'] },
  { emoji: '🎬', name: 'Clapper Board', category: 'Objects', tags: ['movie', 'film', 'clapper'] },
  { emoji: '📺', name: 'Television', category: 'Objects', tags: ['tv', 'television'] },
  { emoji: '📷', name: 'Camera', category: 'Objects', tags: ['camera', 'photo'] },
  { emoji: '📸', name: 'Camera with Flash', category: 'Objects', tags: ['camera', 'photo', 'flash'] },
  { emoji: '📹', name: 'Video Camera', category: 'Objects', tags: ['video', 'camera'] },
  { emoji: '📼', name: 'Videocassette', category: 'Objects', tags: ['vhs', 'tape', 'video'] },
  { emoji: '📞', name: 'Telephone Receiver', category: 'Objects', tags: ['phone', 'telephone', 'call'] },
  { emoji: '☎️', name: 'Telephone', category: 'Objects', tags: ['phone', 'telephone'] },
  { emoji: '📟', name: 'Pager', category: 'Objects', tags: ['pager', 'beeper'] },
  { emoji: '📠', name: 'Fax Machine', category: 'Objects', tags: ['fax', 'machine'] },
  { emoji: '📡', name: 'Satellite Antenna', category: 'Objects', tags: ['satellite', 'antenna', 'dish'] },
  { emoji: '🔋', name: 'Battery', category: 'Objects', tags: ['battery', 'power'] },
  { emoji: '🔌', name: 'Electric Plug', category: 'Objects', tags: ['plug', 'electric', 'power'] },
  { emoji: '💡', name: 'Light Bulb', category: 'Objects', tags: ['bulb', 'light', 'idea'] },
  { emoji: '🔦', name: 'Flashlight', category: 'Objects', tags: ['flashlight', 'torch', 'light'] },
  { emoji: '🕯️', name: 'Candle', category: 'Objects', tags: ['candle', 'light', 'flame'] },
  { emoji: '🔥', name: 'Fire', category: 'Objects', tags: ['fire', 'flame', 'hot'] },
  { emoji: '💸', name: 'Money with Wings', category: 'Objects', tags: ['money', 'wings', 'cash'] },
  { emoji: '💵', name: 'Dollar Banknote', category: 'Objects', tags: ['dollar', 'money', 'cash'] },
  { emoji: '💴', name: 'Yen Banknote', category: 'Objects', tags: ['yen', 'money', 'cash'] },
  { emoji: '💶', name: 'Euro Banknote', category: 'Objects', tags: ['euro', 'money', 'cash'] },
  { emoji: '💷', name: 'Pound Banknote', category: 'Objects', tags: ['pound', 'money', 'cash'] },
  { emoji: '💰', name: 'Money Bag', category: 'Objects', tags: ['money', 'bag', 'rich'] },
  { emoji: '💳', name: 'Credit Card', category: 'Objects', tags: ['credit card', 'card', 'payment'] },
  { emoji: '💎', name: 'Gem Stone', category: 'Objects', tags: ['gem', 'diamond', 'jewel'] },
  { emoji: '⚖️', name: 'Balance Scale', category: 'Objects', tags: ['scale', 'balance', 'justice'] },
  { emoji: '🔧', name: 'Wrench', category: 'Objects', tags: ['wrench', 'tool'] },
  { emoji: '🔨', name: 'Hammer', category: 'Objects', tags: ['hammer', 'tool'] },
  { emoji: '⚒️', name: 'Hammer and Pick', category: 'Objects', tags: ['hammer', 'pick', 'tool'] },
  { emoji: '🛠️', name: 'Hammer and Wrench', category: 'Objects', tags: ['hammer', 'wrench', 'tool'] },
  { emoji: '⛏️', name: 'Pick', category: 'Objects', tags: ['pick', 'tool', 'mining'] },
  { emoji: '🔩', name: 'Nut and Bolt', category: 'Objects', tags: ['nut', 'bolt', 'hardware'] },
  { emoji: '⚙️', name: 'Gear', category: 'Objects', tags: ['gear', 'cog', 'settings'] },
  { emoji: '🔗', name: 'Link', category: 'Objects', tags: ['link', 'chain', 'url'] },
  { emoji: '⛓️', name: 'Chains', category: 'Objects', tags: ['chain', 'metal'] },
  { emoji: '📎', name: 'Paperclip', category: 'Objects', tags: ['paperclip', 'clip', 'office'] },
  { emoji: '✂️', name: 'Scissors', category: 'Objects', tags: ['scissors', 'cut'] },
  { emoji: '📏', name: 'Straight Ruler', category: 'Objects', tags: ['ruler', 'measure'] },
  { emoji: '📐', name: 'Triangular Ruler', category: 'Objects', tags: ['ruler', 'triangle', 'measure'] },
  { emoji: '📌', name: 'Pushpin', category: 'Objects', tags: ['pin', 'pushpin', 'tack'] },
  { emoji: '📍', name: 'Round Pushpin', category: 'Objects', tags: ['pin', 'location', 'place'] },
  { emoji: '🔑', name: 'Key', category: 'Objects', tags: ['key', 'lock'] },
  { emoji: '🔐', name: 'Locked with Key', category: 'Objects', tags: ['lock', 'key', 'secure'] },
  { emoji: '🔒', name: 'Locked', category: 'Objects', tags: ['lock', 'locked', 'secure'] },
  { emoji: '🔓', name: 'Unlocked', category: 'Objects', tags: ['unlock', 'unlocked', 'open'] },
  { emoji: '🔔', name: 'Bell', category: 'Objects', tags: ['bell', 'notification', 'ring'] },
  { emoji: '🔕', name: 'Bell with Slash', category: 'Objects', tags: ['bell', 'mute', 'silent'] },
  { emoji: '🎁', name: 'Wrapped Gift', category: 'Objects', tags: ['gift', 'present', 'box'] },
  { emoji: '🎈', name: 'Balloon', category: 'Objects', tags: ['balloon', 'party'] },
  { emoji: '🎉', name: 'Party Popper', category: 'Objects', tags: ['party', 'celebration', 'confetti'] },
  { emoji: '🎊', name: 'Confetti Ball', category: 'Objects', tags: ['confetti', 'party', 'celebration'] },

  { emoji: '⭐', name: 'Star', category: 'Symbols', tags: ['star', 'favorite'] },
  { emoji: '✨', name: 'Sparkles', category: 'Symbols', tags: ['sparkles', 'shine', 'stars'] },
  { emoji: '💫', name: 'Dizzy', category: 'Symbols', tags: ['dizzy', 'star', 'sparkle'] },
  { emoji: '🔯', name: 'Dotted Six-Pointed Star', category: 'Symbols', tags: ['star', 'david'] },
  { emoji: '✅', name: 'Check Mark Button', category: 'Symbols', tags: ['check', 'done', 'correct'] },
  { emoji: '❌', name: 'Cross Mark', category: 'Symbols', tags: ['x', 'cross', 'wrong'] },
  { emoji: '❎', name: 'Cross Mark Button', category: 'Symbols', tags: ['x', 'cross', 'wrong'] },
  { emoji: '➕', name: 'Plus', category: 'Symbols', tags: ['plus', 'add'] },
  { emoji: '➖', name: 'Minus', category: 'Symbols', tags: ['minus', 'subtract'] },
  { emoji: '➗', name: 'Divide', category: 'Symbols', tags: ['divide', 'division'] },
  { emoji: '✖️', name: 'Multiply', category: 'Symbols', tags: ['multiply', 'times'] },
  { emoji: '💯', name: '100', category: 'Symbols', tags: ['100', 'hundred', 'perfect'] },
  { emoji: '🔴', name: 'Red Circle', category: 'Symbols', tags: ['red', 'circle'] },
  { emoji: '🟠', name: 'Orange Circle', category: 'Symbols', tags: ['orange', 'circle'] },
  { emoji: '🟡', name: 'Yellow Circle', category: 'Symbols', tags: ['yellow', 'circle'] },
  { emoji: '🟢', name: 'Green Circle', category: 'Symbols', tags: ['green', 'circle'] },
  { emoji: '🔵', name: 'Blue Circle', category: 'Symbols', tags: ['blue', 'circle'] },
  { emoji: '🟣', name: 'Purple Circle', category: 'Symbols', tags: ['purple', 'circle'] },
  { emoji: '🟤', name: 'Brown Circle', category: 'Symbols', tags: ['brown', 'circle'] },
  { emoji: '⚫', name: 'Black Circle', category: 'Symbols', tags: ['black', 'circle'] },
  { emoji: '⚪', name: 'White Circle', category: 'Symbols', tags: ['white', 'circle'] },
  { emoji: '🔶', name: 'Large Orange Diamond', category: 'Symbols', tags: ['orange', 'diamond'] },
  { emoji: '🔷', name: 'Large Blue Diamond', category: 'Symbols', tags: ['blue', 'diamond'] },
  { emoji: '🔸', name: 'Small Orange Diamond', category: 'Symbols', tags: ['orange', 'diamond'] },
  { emoji: '🔹', name: 'Small Blue Diamond', category: 'Symbols', tags: ['blue', 'diamond'] },
  { emoji: '💠', name: 'Diamond with a Dot', category: 'Symbols', tags: ['diamond', 'flower'] },
  { emoji: '🔘', name: 'Radio Button', category: 'Symbols', tags: ['radio', 'button', 'circle'] },
  { emoji: '🔳', name: 'White Square Button', category: 'Symbols', tags: ['white', 'square', 'button'] },
  { emoji: '🔲', name: 'Black Square Button', category: 'Symbols', tags: ['black', 'square', 'button'] },
  { emoji: '♠️', name: 'Spade Suit', category: 'Symbols', tags: ['spade', 'cards', 'suit'] },
  { emoji: '♣️', name: 'Club Suit', category: 'Symbols', tags: ['club', 'cards', 'suit'] },
  { emoji: '♥️', name: 'Heart Suit', category: 'Symbols', tags: ['heart', 'cards', 'suit'] },
  { emoji: '♦️', name: 'Diamond Suit', category: 'Symbols', tags: ['diamond', 'cards', 'suit'] },
  { emoji: '🃏', name: 'Joker', category: 'Symbols', tags: ['joker', 'card', 'wild'] },
  { emoji: '🎴', name: 'Flower Playing Cards', category: 'Symbols', tags: ['cards', 'flower', 'japanese'] },
  { emoji: '🀄', name: 'Mahjong Red Dragon', category: 'Symbols', tags: ['mahjong', 'red', 'dragon'] },
  { emoji: '🔇', name: 'Muted Speaker', category: 'Symbols', tags: ['mute', 'speaker', 'sound'] },
  { emoji: '🔈', name: 'Speaker Low Volume', category: 'Symbols', tags: ['speaker', 'sound', 'volume'] },
  { emoji: '🔉', name: 'Speaker Medium Volume', category: 'Symbols', tags: ['speaker', 'sound', 'volume'] },
  { emoji: '🔊', name: 'Speaker High Volume', category: 'Symbols', tags: ['speaker', 'sound', 'volume', 'loud'] },
  { emoji: '📢', name: 'Loudspeaker', category: 'Symbols', tags: ['loudspeaker', 'announcement'] },
  { emoji: '📣', name: 'Megaphone', category: 'Symbols', tags: ['megaphone', 'announcement'] },
  { emoji: '🔔', name: 'Bell', category: 'Symbols', tags: ['bell', 'notification'] },
  { emoji: '🔕', name: 'Bell with Slash', category: 'Symbols', tags: ['bell', 'mute', 'notification'] },
  { emoji: '🎵', name: 'Musical Note', category: 'Symbols', tags: ['music', 'note'] },
  { emoji: '🎶', name: 'Musical Notes', category: 'Symbols', tags: ['music', 'notes'] },
  { emoji: '💤', name: 'Zzz', category: 'Symbols', tags: ['sleep', 'zzz', 'sleepy'] },
  { emoji: '💢', name: 'Anger Symbol', category: 'Symbols', tags: ['anger', 'mad', 'comic'] },
  { emoji: '💬', name: 'Speech Balloon', category: 'Symbols', tags: ['speech', 'balloon', 'chat'] },
  { emoji: '💭', name: 'Thought Balloon', category: 'Symbols', tags: ['thought', 'balloon', 'think'] },
  { emoji: '🗯️', name: 'Right Anger Bubble', category: 'Symbols', tags: ['anger', 'bubble', 'comic'] },
  { emoji: '♨️', name: 'Hot Springs', category: 'Symbols', tags: ['hot', 'springs', 'steam'] },
  { emoji: '🚫', name: 'Prohibited', category: 'Symbols', tags: ['prohibited', 'no', 'banned'] },
  { emoji: '⛔', name: 'No Entry', category: 'Symbols', tags: ['no entry', 'stop'] },
  { emoji: '🚷', name: 'No Pedestrians', category: 'Symbols', tags: ['no', 'pedestrians', 'walking'] },
  { emoji: '🚭', name: 'No Smoking', category: 'Symbols', tags: ['no smoking', 'cigarette'] },
  { emoji: '⚠️', name: 'Warning', category: 'Symbols', tags: ['warning', 'caution', 'alert'] },
  { emoji: '⚡', name: 'High Voltage', category: 'Symbols', tags: ['lightning', 'electric', 'voltage'] },
  { emoji: '☢️', name: 'Radioactive', category: 'Symbols', tags: ['radioactive', 'danger', 'nuclear'] },
  { emoji: '☣️', name: 'Biohazard', category: 'Symbols', tags: ['biohazard', 'danger'] },
  { emoji: '🔞', name: 'No One Under Eighteen', category: 'Symbols', tags: ['18+', 'adult', 'age'] },
  { emoji: '♻️', name: 'Recycling Symbol', category: 'Symbols', tags: ['recycle', 'green', 'eco'] },
  { emoji: '⚕️', name: 'Medical Symbol', category: 'Symbols', tags: ['medical', 'health', 'medicine'] },
  { emoji: '♿', name: 'Wheelchair Symbol', category: 'Symbols', tags: ['wheelchair', 'accessible', 'handicap'] },
  { emoji: '🚹', name: 'Mens Room', category: 'Symbols', tags: ['men', 'bathroom', 'restroom'] },
  { emoji: '🚺', name: 'Womens Room', category: 'Symbols', tags: ['women', 'bathroom', 'restroom'] },
  { emoji: '🚻', name: 'Restroom', category: 'Symbols', tags: ['restroom', 'bathroom', 'toilet'] },
  { emoji: '🚼', name: 'Baby Symbol', category: 'Symbols', tags: ['baby', 'infant'] },
  { emoji: '🚾', name: 'Water Closet', category: 'Symbols', tags: ['wc', 'toilet', 'bathroom'] },
  { emoji: '⬆️', name: 'Up Arrow', category: 'Symbols', tags: ['up', 'arrow', 'direction'] },
  { emoji: '↗️', name: 'Up-Right Arrow', category: 'Symbols', tags: ['up', 'right', 'arrow', 'direction'] },
  { emoji: '➡️', name: 'Right Arrow', category: 'Symbols', tags: ['right', 'arrow', 'direction'] },
  { emoji: '↘️', name: 'Down-Right Arrow', category: 'Symbols', tags: ['down', 'right', 'arrow', 'direction'] },
  { emoji: '⬇️', name: 'Down Arrow', category: 'Symbols', tags: ['down', 'arrow', 'direction'] },
  { emoji: '↙️', name: 'Down-Left Arrow', category: 'Symbols', tags: ['down', 'left', 'arrow', 'direction'] },
  { emoji: '⬅️', name: 'Left Arrow', category: 'Symbols', tags: ['left', 'arrow', 'direction'] },
  { emoji: '↖️', name: 'Up-Left Arrow', category: 'Symbols', tags: ['up', 'left', 'arrow', 'direction'] },
  { emoji: '↕️', name: 'Up-Down Arrow', category: 'Symbols', tags: ['up', 'down', 'arrow', 'vertical'] },
  { emoji: '↔️', name: 'Left-Right Arrow', category: 'Symbols', tags: ['left', 'right', 'arrow', 'horizontal'] },
  { emoji: '↩️', name: 'Right Arrow Curving Left', category: 'Symbols', tags: ['arrow', 'return', 'back'] },
  { emoji: '↪️', name: 'Left Arrow Curving Right', category: 'Symbols', tags: ['arrow', 'forward'] },
  { emoji: '⤴️', name: 'Right Arrow Curving Up', category: 'Symbols', tags: ['arrow', 'up'] },
  { emoji: '⤵️', name: 'Right Arrow Curving Down', category: 'Symbols', tags: ['arrow', 'down'] },
  { emoji: '🔃', name: 'Clockwise Vertical Arrows', category: 'Symbols', tags: ['arrows', 'reload', 'refresh'] },
  { emoji: '🔄', name: 'Counterclockwise Arrows Button', category: 'Symbols', tags: ['arrows', 'reload', 'refresh'] },
  { emoji: '🔙', name: 'Back Arrow', category: 'Symbols', tags: ['back', 'arrow'] },
  { emoji: '🔚', name: 'End Arrow', category: 'Symbols', tags: ['end', 'arrow'] },
  { emoji: '🔛', name: 'On! Arrow', category: 'Symbols', tags: ['on', 'arrow'] },
  { emoji: '🔜', name: 'Soon Arrow', category: 'Symbols', tags: ['soon', 'arrow'] },
  { emoji: '🔝', name: 'Top Arrow', category: 'Symbols', tags: ['top', 'arrow', 'up'] },

  { emoji: '🌍', name: 'Globe Showing Europe-Africa', category: 'Nature', tags: ['earth', 'world', 'globe'] },
  { emoji: '🌎', name: 'Globe Showing Americas', category: 'Nature', tags: ['earth', 'world', 'globe'] },
  { emoji: '🌏', name: 'Globe Showing Asia-Australia', category: 'Nature', tags: ['earth', 'world', 'globe'] },
  { emoji: '🌐', name: 'Globe with Meridians', category: 'Nature', tags: ['globe', 'world', 'internet'] },
  { emoji: '🌑', name: 'New Moon', category: 'Nature', tags: ['moon', 'dark'] },
  { emoji: '🌒', name: 'Waxing Crescent Moon', category: 'Nature', tags: ['moon', 'crescent'] },
  { emoji: '🌓', name: 'First Quarter Moon', category: 'Nature', tags: ['moon', 'quarter'] },
  { emoji: '🌔', name: 'Waxing Gibbous Moon', category: 'Nature', tags: ['moon', 'gibbous'] },
  { emoji: '🌕', name: 'Full Moon', category: 'Nature', tags: ['moon', 'full'] },
  { emoji: '🌖', name: 'Waning Gibbous Moon', category: 'Nature', tags: ['moon', 'gibbous'] },
  { emoji: '🌗', name: 'Last Quarter Moon', category: 'Nature', tags: ['moon', 'quarter'] },
  { emoji: '🌘', name: 'Waning Crescent Moon', category: 'Nature', tags: ['moon', 'crescent'] },
  { emoji: '🌙', name: 'Crescent Moon', category: 'Nature', tags: ['moon', 'crescent', 'night'] },
  { emoji: '🌚', name: 'New Moon Face', category: 'Nature', tags: ['moon', 'face', 'dark'] },
  { emoji: '🌛', name: 'First Quarter Moon Face', category: 'Nature', tags: ['moon', 'face'] },
  { emoji: '🌜', name: 'Last Quarter Moon Face', category: 'Nature', tags: ['moon', 'face'] },
  { emoji: '🌝', name: 'Full Moon Face', category: 'Nature', tags: ['moon', 'face', 'full'] },
  { emoji: '☀️', name: 'Sun', category: 'Nature', tags: ['sun', 'sunny', 'day'] },
  { emoji: '🌞', name: 'Sun with Face', category: 'Nature', tags: ['sun', 'face', 'sunny'] },
  { emoji: '⭐', name: 'Star', category: 'Nature', tags: ['star', 'night'] },
  { emoji: '🌟', name: 'Glowing Star', category: 'Nature', tags: ['star', 'shine', 'glow'] },
  { emoji: '💫', name: 'Dizzy', category: 'Nature', tags: ['dizzy', 'star', 'sparkle'] },
  { emoji: '✨', name: 'Sparkles', category: 'Nature', tags: ['sparkles', 'shine', 'stars'] },
  { emoji: '☁️', name: 'Cloud', category: 'Nature', tags: ['cloud', 'weather'] },
  { emoji: '⛅', name: 'Sun Behind Cloud', category: 'Nature', tags: ['sun', 'cloud', 'partly cloudy'] },
  { emoji: '⛈️', name: 'Cloud with Lightning and Rain', category: 'Nature', tags: ['storm', 'thunder', 'lightning'] },
  { emoji: '🌤️', name: 'Sun Behind Small Cloud', category: 'Nature', tags: ['sun', 'cloud', 'weather'] },
  { emoji: '🌥️', name: 'Sun Behind Large Cloud', category: 'Nature', tags: ['sun', 'cloud', 'weather'] },
  { emoji: '🌦️', name: 'Sun Behind Rain Cloud', category: 'Nature', tags: ['sun', 'rain', 'cloud'] },
  { emoji: '🌧️', name: 'Cloud with Rain', category: 'Nature', tags: ['rain', 'cloud', 'weather'] },
  { emoji: '🌨️', name: 'Cloud with Snow', category: 'Nature', tags: ['snow', 'cloud', 'weather'] },
  { emoji: '🌩️', name: 'Cloud with Lightning', category: 'Nature', tags: ['lightning', 'cloud', 'thunder'] },
  { emoji: '🌪️', name: 'Tornado', category: 'Nature', tags: ['tornado', 'cyclone', 'storm'] },
  { emoji: '🌫️', name: 'Fog', category: 'Nature', tags: ['fog', 'mist', 'weather'] },
  { emoji: '🌬️', name: 'Wind Face', category: 'Nature', tags: ['wind', 'blow', 'face'] },
  { emoji: '🌀', name: 'Cyclone', category: 'Nature', tags: ['cyclone', 'hurricane', 'storm'] },
  { emoji: '🌈', name: 'Rainbow', category: 'Nature', tags: ['rainbow', 'colors', 'weather'] },
  { emoji: '🌂', name: 'Closed Umbrella', category: 'Nature', tags: ['umbrella', 'rain'] },
  { emoji: '☂️', name: 'Umbrella', category: 'Nature', tags: ['umbrella', 'rain'] },
  { emoji: '☔', name: 'Umbrella with Rain Drops', category: 'Nature', tags: ['umbrella', 'rain', 'weather'] },
  { emoji: '⛱️', name: 'Umbrella on Ground', category: 'Nature', tags: ['umbrella', 'beach', 'sun'] },
  { emoji: '⚡', name: 'High Voltage', category: 'Nature', tags: ['lightning', 'electric', 'bolt'] },
  { emoji: '❄️', name: 'Snowflake', category: 'Nature', tags: ['snow', 'snowflake', 'cold'] },
  { emoji: '☃️', name: 'Snowman', category: 'Nature', tags: ['snowman', 'snow', 'winter'] },
  { emoji: '⛄', name: 'Snowman Without Snow', category: 'Nature', tags: ['snowman', 'winter'] },
  { emoji: '☄️', name: 'Comet', category: 'Nature', tags: ['comet', 'space', 'meteor'] },
  { emoji: '🔥', name: 'Fire', category: 'Nature', tags: ['fire', 'flame', 'hot'] },
  { emoji: '💧', name: 'Droplet', category: 'Nature', tags: ['water', 'drop', 'droplet'] },
  { emoji: '🌊', name: 'Water Wave', category: 'Nature', tags: ['wave', 'water', 'ocean'] },
  { emoji: '🌲', name: 'Evergreen Tree', category: 'Nature', tags: ['tree', 'evergreen', 'pine'] },
  { emoji: '🌳', name: 'Deciduous Tree', category: 'Nature', tags: ['tree', 'deciduous'] },
  { emoji: '🌴', name: 'Palm Tree', category: 'Nature', tags: ['palm', 'tree', 'tropical'] },
  { emoji: '🌵', name: 'Cactus', category: 'Nature', tags: ['cactus', 'desert', 'plant'] },
  { emoji: '🌾', name: 'Sheaf of Rice', category: 'Nature', tags: ['rice', 'grain', 'wheat'] },
  { emoji: '🌿', name: 'Herb', category: 'Nature', tags: ['herb', 'leaf', 'plant'] },
  { emoji: '☘️', name: 'Shamrock', category: 'Nature', tags: ['shamrock', 'clover', 'irish'] },
  { emoji: '🍀', name: 'Four Leaf Clover', category: 'Nature', tags: ['clover', 'lucky', 'four leaf'] },
  { emoji: '🍁', name: 'Maple Leaf', category: 'Nature', tags: ['maple', 'leaf', 'fall'] },
  { emoji: '🍂', name: 'Fallen Leaf', category: 'Nature', tags: ['leaf', 'fall', 'autumn'] },
  { emoji: '🍃', name: 'Leaf Fluttering in Wind', category: 'Nature', tags: ['leaf', 'wind', 'flutter'] },
  { emoji: '🌺', name: 'Hibiscus', category: 'Nature', tags: ['hibiscus', 'flower', 'tropical'] },
  { emoji: '🌻', name: 'Sunflower', category: 'Nature', tags: ['sunflower', 'flower', 'sun'] },
  { emoji: '🌼', name: 'Blossom', category: 'Nature', tags: ['blossom', 'flower'] },
  { emoji: '🌷', name: 'Tulip', category: 'Nature', tags: ['tulip', 'flower'] },
  { emoji: '🌸', name: 'Cherry Blossom', category: 'Nature', tags: ['cherry', 'blossom', 'flower', 'sakura'] },
  { emoji: '🌹', name: 'Rose', category: 'Nature', tags: ['rose', 'flower', 'love'] },
  { emoji: '🥀', name: 'Wilted Flower', category: 'Nature', tags: ['wilted', 'flower', 'dead'] },
  { emoji: '🌺', name: 'Hibiscus', category: 'Nature', tags: ['hibiscus', 'flower'] },
  { emoji: '💐', name: 'Bouquet', category: 'Nature', tags: ['bouquet', 'flowers'] },
  { emoji: '🍄', name: 'Mushroom', category: 'Nature', tags: ['mushroom', 'fungus'] },
  { emoji: '🌰', name: 'Chestnut', category: 'Nature', tags: ['chestnut', 'nut'] },
  { emoji: '🦀', name: 'Crab', category: 'Nature', tags: ['crab', 'sea', 'shellfish'] },
  { emoji: '🐚', name: 'Spiral Shell', category: 'Nature', tags: ['shell', 'sea', 'spiral'] },
];

export const categories = Array.from(new Set(emojiData.map(e => e.category)));
